#!/bin/sh

sxhkd &

bspc monitor DP-0 -d I II III
bspc monitor DP-2 -d IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart
xsetroot -cursor_name left_ptr &
setxkbmap fi &
xscreensaver -nosplash
#xcompmgr -C &
picom -b -C --config /home/patrik/.config/picom/picom.conf
feh --bg-scale /home/patrik/Kuvat/seal.jpg &
${HOME}/.config/polybar/launch.sh &
