#!/bin/sh

# autostart programs
sxhkd & # keybingins
xsetroot -cursor_name left_ptr & # cursor pointer
picom & # compositor
feh --bg-scale /home/patrik/Kuvat/Taustakuvat/Winter-1080p.jpg & # background
$HOME/.config/polybar/launch.sh # polybar

# monitors and workspaces
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width               2
bspc config window_gap                 4
bspc config top_padding                20
bspc config bottom_padding             0
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             false
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config click_to_focus             false
bspc config focus_follows_pointer      true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier           mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# 60hz refresh rate
bspc config pointer_motion_interval 17

# 144hz refresh rate
# bspc config pointer_motion_interval 7

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
